### ISSUE TITLE
Allow targets to be compiled separately?

### ISSUE THREAD

**Issue by makoConstruct** [LOFI/gdx-scala-demo#1]
It was annoying to have to find my way to android/build.gradle and change the sdk version number just to get it to compile the desktop target. Can we get gradlew to accept target name arguments and ignore dependencies for the other projects?

**Comment by makoConstruct** [comment]
OK.. `./gradlew` is finishing but it isn't producing any target files, and `gradle` (version 1.5 so maybe that's an issue(thanks debian)) is yeilding

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/mako/programming/starry/src/gdx-scala-demo/build.gradle' line: 47

* What went wrong:
A problem occurred evaluating root project 'gdx-scala-demo'.
> Could not create plugin of type 'AppPlugin'.
```

Am I doing this wrong? If so could you please give specific commands to use somewhere?

**Comment by onelson** [comment]
Seems like something could be funky, but I'm not sure what. Normally, using the provided `gradlew` means the wrapper will download the appropriate version of gradle for you (which would be the from the 2.x line).

As far as I know, you should be able to skip compiling one target or another by prefixing the task name with a project name, so for example `./gradlew desktop:run` to build and run desktop only. You can invoke `./gradlew -q tasks --all` to get a display of all the available tasks and which projects they belong to (see: https://docs.gradle.org/current/userguide/tutorial_gradle_command_line.html for more on gradle cli usage).

**Comment by photex** [comment]
I haven't used this with a Gradle previous to 2.x that I'm aware of. That might be the issue. ./gradlew is all I use and I don't have another gradle anywhere on the path.

**Comment by makoConstruct** [comment]
Ah... `./gradlew desktop:run` does work and does avoid whatever problems the android build might have, and `./gradlew -q tasks --all` gets reasonable output.
However, new libgdx developers will never have heard of those commands. They will run `./gradlew -h`, which will then recommend `./gradlew tasks`, and that will only mislead them. They should be advised in the readme that this demo will not be informative until they've gone through https://github.com/libgdx/libgdx/wiki/Project-Setup-Gradle and the like, as nowhere is there any indication that there is this requirement of prior knowledge.

**Comment by onelson** [comment]
There is some unfortunate added complexity when going from single project to multi-project gradle builds. 

I'm sort of torn on this, just because I don't think it's libgdx's job to document gradle usage (just as it's not their job to teach you java, or scala). At the same time, a listing of the main gradle tasks and a short description in the docs would be good to have.

**Comment by makoConstruct** [comment]
I have never seen a project where the average contributor needs to know anything more about the build system than two or three commands, it is not reasonable to point them to the documentation of the build system when that is all they need.

**Comment by photex** [comment]
https://github.com/libgdx/libgdx/wiki/Gradle-on-the-Commandline

The wiki has some good examples though. If it would be helpful we could update our README here with some links to the relevant sections if people are new to libGDX, but for the most part this repo is ancillary and only here to provide the parts needed to use Scala.
