### ISSUE TITLE
Can't build android project

### ISSUE THREAD

**Issue by KonstantTom** [LOFI/gdx-scala-demo#2]
I can't run android project. I don't do anything, but dex loader can not convert this whole project. 
Please, fix this.

```
[2015-08-25 14:39:42 - gdx-scala-demo-android] Dx 
trouble writing output: already prepared
[2015-08-25 14:39:44 - Dex Loader] Unable to execute dex: method ID not in [0, 0xffff]: 65536
[2015-08-25 14:39:44 - gdx-scala-demo-android] Conversion to Dalvik format failed: Unable to execute dex: method ID not in [0, 0xffff]: 65536
```

**Comment by photex** [comment]
Hi @KonstantTom could you tell me more about your environment? Like what OS, JVM version, and so on.

**Comment by KonstantTom** [comment]
Hi @photex ! Windows 7 SP1 x64 . Java vesrion 1.7.0_75. Scala IDE 4.1.1-vfinal-20150727-1320-Typesafe on Eclipse 4.3.0 .
All installed eclipse software list:

   **Android DDMS** 23.0.6.1720515  com.android.ide.eclipse.ddms.feature.feature.group  The Android Open Source Project

   **Android Development Tools**    23.0.6.1720515  com.android.ide.eclipse.adt.feature.feature.group   The Android Open Source Project

  **Android Hierarchy Viewer**  23.0.6.1720515  com.android.ide.eclipse.hierarchyviewer.feature.feature.group   The Android Open Source Project
  **Android Native Development Tools**  23.0.6.1720515  com.android.ide.eclipse.ndk.feature.feature.group   The Android Open Source Project
  **Android Traceview** 23.0.6.1720515  com.android.ide.eclipse.traceview.feature.feature.group The Android Open Source Project
 **Android/Proguard/Scala Feature** 0.0.51  com.restphone.androidproguardscala.feature.feature.group    null

**Eclipse Color Theme** 1.0.0.201410260308  com.github.eclipsecolortheme.feature.feature.group  GitHub

  **Gradle IDE**    3.7.1.201507271623-CI-B46   org.springsource.ide.eclipse.gradle.feature.feature.group   Pivotal Software, Inc.

 **m2e - Maven Integration for Eclipse (includes Incubating components)**   1.6.1.20150625-2338 org.eclipse.m2e.feature.feature.group   Eclipse.org - m2e

**Maven Integration for Scala IDE** 0.5.1.201410131304  org.maven.ide.eclipse.scala_feature.feature.group   Sonatype, Inc.

 **Play2 support in Scala IDE** 0.4.6.v-2_11-201507271109-cb3cdb8   org.scala-ide.play2.feature.feature.group   Scala IDE

**Scala 2.11.7**    4.1.1.201507261042  org.scala-ide.scala211.feature.feature.group    scala-ide.org

**Scala 2.11.7 sources**    4.1.1.201507261042  org.scala-ide.scala211.source.feature.feature.group scala-ide.org

**Scala IDE for Eclipse**   4.1.1.v-2_11-201507261049-bc34267   org.scala-ide.sdt.feature.feature.group scala-ide.org

 **Scala SDK**  4.1.0.201507271127  org.scala-ide.sdk.feature.feature.group scala-ide.org

 **Scala Worksheet**    0.3.0.v-2_11-201507271104-4fe32b5   org.scalaide.worksheet.feature.feature.group    Scala IDE

**ScalaTest for Scala IDE** 2.9.3.v-4-2_11-201507090333-a29ebef org.scala-ide.sdt.scalatest.feature.feature.group   scala-ide.org

**Tracer for OpenGL ES**    23.0.6.1720515  com.android.ide.eclipse.gldebugger.feature.feature.group    The Android Open Source Project

**Typesafe Scala IDE**  1.0.0.201507271127  scalaide.product.id null

**Comment by photex** [comment]
Awesome, thanks for the details. I have access to OSX, Win10 and an Ubuntu system so I can't replicate your setup exactly. However, I'll make sure I go through the build again on my windows machine with JDK 7. I've been using JDK8 this whole time and that's the most obvious place for me to start looking I think.
Other than that I usually test the build using the gradle wrapper and not an IDE. Have you tried the build from powershell or cmd.exe using gradlew.bat to see if the same error occurs?

**Comment by KonstantTom** [comment]
No, i don't. I never work with gradle from cmd.

**Comment by photex** [comment]
If you get a moment could you give it a try? I'm asking because we specifically configure the android build to avoid this exact bug and if it's working for you on the command line but not in Eclipse then we know to spend time looking into how the IDE is configured by this project.
In either case I'll give it all a shot as soon as I'm off work. :)

**Comment by KonstantTom** [comment]
Ok, i will try.

**Comment by KonstantTom** [comment]
Thanks. :+1: 
android:build task works correctly and application working sucessfully.
Now i will learn how to sign and zipalign application from cmd. :)

**Comment by photex** [comment]
Cool! Glad that it's working for you. :)
